### ISSUE TITLE
Functions missing

### ISSUE THREAD

**Issue by amikebous** [NuytsSiegmund/CoastCams#1]
Thank you very much for sharing the code and the repo. I am contacting you about some bugs that I noticed:
- there are some functions missing: LinearC, smooth2
- the example you provide doesn't produce bathymetry, all the depth related variables have only nans
- the img_path needs to be added in the lines where the image is read; e.g. line 90 (Timestack = imread(fullfile(img_path,Img(i).name));) and line 166 (as input for WaveParameters_CoastCams)

**Comment by NuytsSiegmund** [comment]
Thanks for highlighting this.
This issue should be resolved now
